Project opdracht4{
    database_type: 'MySQL'
    Note: 'opdracht 4 voor database lessen'
}

// comment BasicLog {
//     Id INT [pk, increment]
//     IsActief BIT(1) [NOT NULL, DEFAULT: 1]
//     Opmerking VARCHAR(255) [NULL]
//     DatumAangemaakt DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
//     DatumGewijzigd DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
// }

Table Bank{
    Id INT [pk, increment]
    Naam VARCHAR(50) [NOT NULL, UNIQUE]
    Telefoonnummer VARCHAR(15) [NOT NULL]
    Email VARCHAR(50) [NOT NULL]
    Vestigingsdatum DATETIME(6) [NOT NULL]
    IsActief BIT(1) [NOT NULL, DEFAULT: 1]
    Opmerking VARCHAR(255) [NULL]
    DatumAangemaakt DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
    DatumGewijzigd DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
}

Table Klant{
    Id INT [pk, increment]
    Voornaam VARCHAR(50) [NOT NULL]
    Tussenvoegsel VARCHAR(50) [NULL]
    Achternaam VARCHAR(50) [NOT NULL]
    Geboortedatum DATE [NOT NULL]
    mobiel VARCHAR(15) [NOT NULL]
    email VARCHAR(50) [NOT NULL]
    IsActief BIT(1) [NOT NULL, DEFAULT: 1]
    Opmerking VARCHAR(255) [NULL]
    DatumAangemaakt DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
    DatumGewijzigd DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
}

Table Rekening{
    Id INT [pk, increment]
    Rekeningnummer CHAR(10) [NOT NULL, UNIQUE]
    rekeningType ENUM('Spaarrekening', 'Betaalrekening', 'Zakelijke rekening') [NOT NULL]
    Saldo DECIMAL(15,2) [NOT NULL, DEFAULT: 0.00]
    openingsdatum DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
    BankId INT [NOT NULL, ref: > Bank.Id]
    KlantId INT [NOT NULL, ref: > Klant.Id]
    IsActief BIT(1) [NOT NULL, DEFAULT: 1]
    Opmerking VARCHAR(255) [NULL]
    DatumAangemaakt DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
    DatumGewijzigd DATETIME(6) [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP`]
}